### PR TITLE
separate benchmark package to reduce dependency

### PR DESCRIPTION
**Pull request by Songmu**
# Overview

I separated the package from the module because I didn't want to add more dependent libraries for benchmarking purposes when there are so few dependencies.

# Changes

# Impact range

# Operational Requirements

# Related Issue

# Supplement

### CODE REVIEW

**Comment by bmf-san** [comment]
@Songmu 
Thank you for your PR!  I will confirm it and reply back as soon as possible.

**Comment by bmf-san** [comment]
@Songmu 
LGTM :)
When I merged https://github.com/bmf-san/goblin/pull/16, conflicts has occurred.
So could you resolve the conflict?  Then I'll merge this.

**Comment by Songmu** [comment]
resolved! @bmf-san

**Comment by bmf-san** [comment]
@Songmu 
Thanks! I'll merge it!

**Pull request merged**
